import os

print('------------- OS模块的使用 -------------')

print('------------- 打印当前工作目录 -------------')
print(os.getcwd())
print('------------- 改变工作目录 -------------')
# os.chdir('c:/xxxx')
print('------------- 列举制定目录的文件名 -------------')
print(os.listdir('c:/'))
print('------------- 创建单层目录 -------------')
# os.mkdir('c:/aaa')
print('------------- 递归创建多层目录，如该目录存在则会抛出异常 -------------')
# os.makedirs('c:/aaa/bbb')
print('------------- 删除文件 -------------')
# os.remove('../filetest/test.txt')
print('------------- 删除单层文件夹（如遇目录非空则会抛出异常） -------------')
# os.rmdir('c:/aaa')
print('------------- 删除多层文件夹（如遇目录非空则会抛出异常） -------------')
# os.rmdir('c:/aaa/bbb')
print('------------- 将文件old重命名为new -------------')
# os.rename('c:/aaa','c:/bbb')
print('------------- 运行系统的shell命令 -------------')
#os.system('calc')

print('\n------------- 跨平台定义语义 -------------')
print(os.curdir,'指代当前目录\'.\'')
print(os.pardir,'指代上一级目录\'..\'')
print(os.sep,'输出操作系统特定的路径分隔符（win下为\' \\ \',Linux下为\' / \'）')
print(os.name,'显示当前操作系统')

print('\n------------- os.path模块中关于路径常用的函数使用方法 -------------')
print(os.path.basename('../filetest/test.txt'),'去掉目录路径，单独返回文件名')
print(os.path.dirname('../filetest/test.txt'),'去掉文件名，单独返回目录路径')
